/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MxcdSideDrawer {
    'open': () => Promise<void>;
    'opened': boolean;
    'sideTitle': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLMxcdSideDrawerElement extends Components.MxcdSideDrawer, HTMLStencilElement {}
  var HTMLMxcdSideDrawerElement: {
    prototype: HTMLMxcdSideDrawerElement;
    new (): HTMLMxcdSideDrawerElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'mxcd-side-drawer': HTMLMxcdSideDrawerElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface MxcdSideDrawer {
    'opened'?: boolean;
    'sideTitle'?: string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'mxcd-side-drawer': MxcdSideDrawer;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'mxcd-side-drawer': LocalJSX.MxcdSideDrawer & JSXBase.HTMLAttributes<HTMLMxcdSideDrawerElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
    }
  }
}


